---
- model_name: 'usv'
  model_type: 'usv'
  position:
    xyz: [-1462.0, -16.5, 0.3]
    rpy: [0, 0, 0]

- model_name: 'hunter_0'
  model_type: 'mbzirc_quadrotor'
  flight_time: 60
  position:
    xyz: [-1462.0, -17.7, 0.9]
    rpy: [0, 0, 0]
  payload:
    slot0:
      sensor: 'mbzirc_hd_camera'
      rpy: [0, 0, 0]

- model_name: 'hunter_1'
  model_type: 'mbzirc_quadrotor'
  flight_time: 60
  position:
    xyz: [-1462.0, -15.3, 0.9]
    rpy: [0, 0, 0]
  payload:
    slot0:
      sensor: 'mbzirc_hd_camera'
      rpy: [0, 0, 0]

- model_name: 'drone_sim_4'
  model_type: 'mbzirc_quadrotor'
  flight_time: 60
  position:
    xyz: [-1462.0, -16.5, 0.9]
    rpy: [0, 0, 0]
  payload:
    slot0:
      sensor: 'mbzirc_hd_camera'
      rpy: [0, 0, 0]

- model_name: 'beacon_0'
  model_type: 'mbzirc_quadrotor'
  flight_time: 60
  position:
    xyz: [-1475.0, 2.0, 4.2]
    rpy: [0, 0, 0]
  payload:
    slot0:
      sensor: 'mbzirc_hd_camera'
      rpy: [0, 0, 0]

- model_name: 'beacon_1'
  model_type: 'mbzirc_quadrotor'
  flight_time: 60
  position:
    xyz: [-1475.0, -2.0, 4.2]
    rpy: [0, 0, 0]
  payload:
    slot0:
      sensor: 'mbzirc_hd_camera'
      rpy: [0, 0, 0]
